### ISSUE TITLE
Not Getting Any Output Files

### ISSUE THREAD

**Issue by Nirmal2310** [ParBLiSS/refcom#1]
Hi, I am trying to use this tool for compressing the paired end fastq reads and I had setup this tool on a cluster but after the completion I am not getting any output files. It will be very helpful to me if you could help me out.
I am attaching the screenshots of the log file as well as the command I used. If you need anything else please let me know.
Thank you so much.
![1](https://user-images.githubusercontent.com/62856422/140907974-ca54086b-316d-46e7-837d-c5f1c56cf664.JPG)
![2](https://user-images.githubusercontent.com/62856422/140907977-0b3cf030-0ade-4ce7-aa1c-91d871aed36a.JPG)
![3](https://user-images.githubusercontent.com/62856422/140907960-5535c927-5571-404c-82d4-2edfbe1c4e47.JPG)
![4](https://user-images.githubusercontent.com/62856422/140907973-eb47e0c3-0bb1-4e1a-8e7d-b64f9e83e4d5.JPG)

**Comment by srirampc** [comment]
The error message at the bottom "libbsc/bsc: No such file or directory" implies that the executable is not able to find the "bsc" executable. This executable should be made available under the libbsc directory. Please check if its present at the location. You may need to compile it with make, if not already done.

**Comment by Nirmal2310** [comment]
Thank you for your quick response. I actually done the things instructed on the repository and I also added the path of both REFCOM as well as bsc in my bashrc file but it is still giving me the same results. Please it will be great help if you look into it. Thank you.

**Comment by srirampc** [comment]
Unfortunately, with the way how REFCOM is coded, adding it to the PATH doesn't work. You need to provide the full path when you run. For example, if REFCOM is compiled and built inside "$HOME/refcom" directory, you have to run it as "$HOME/refcom/REFCOM".

**Comment by Nirmal2310** [comment]
Yeah it worked when I provided the complete path. Thank you so much for your help.
