### ISSUE TITLE
refcom compression failed in aligned reads process with error "Command terminated by signal 11"

### ISSUE THREAD

**Issue by foodlover1995** [ParBLiSS/refcom#2]
Hi, I am trying to use this tool for compressing the paired end fastq reads with google-brain-genomics-public datasets. The compression process ends with error "Command terminated by signal 11" during aligned reads. Could you help me understand what caused the issue? I would like to express my sincere appreciation if you could help me out.
Here are an example logs. If you need anything else please let me know.
Thank you so much.

Operation          : compression
Ref File Name      : /Homo_sapiens_assembly38.fasta
Rd1 File Name      : /testRefCom/HG001.novaseq.pcr-free.20x.R1.fastq.gz
Rd2 File Name      : /testRefCom/HG001.novaseq.pcr-free.20x.R2.fastq.gz
Com File Name      : /testRefCom/HG001.novaseq.pcr-free.20x.-compressed
Thread Count       : 32

Reference scaffold_count  : 3366
Reference all_bases_count : 3217346917
Reference val_bases_count : 3043453468
Reference adj_bases_count : 3043453308
Loaded reference into memory in 19.6461 s.
CPU time : 9.30822 s.
lookup_table size is     : 268435457
occurrence_table size is : 3043453295
Created threads for construct-index-1 successfully
Threads for construct-index-1 completed successfully
Before parallel sort
After parallel sort
Created threads for construct-index-2 successfully
Threads for construct-index-2 completed successfully
lookup_table[ 0] : 0
lookup_table[ 1] : 1497904
lookup_table[-2] : 3041945510
lookup_table[-1] : 3043453295
Built index in 265.751 s.
CPU time : 488.01 s.
Created threads for align-reads-1 successfully
Reference scaffold_count  : 3366
Reference all_bases_count : 3217346917
Reference val_bases_count : 3043453468
Reference adj_bases_count : 3043453308
Loaded reference into memory in 5.47428 s.
CPU time : 5.4753 s.
lookup_table size is     : 268435457
occurrence_table size is : 3043453295
Created threads for construct-index-1 successfully
Threads for construct-index-1 completed successfully
Before parallel sort
After parallel sort
Created threads for construct-index-2 successfully
Threads for construct-index-2 completed successfully
lookup_table[ 0] : 0
lookup_table[ 1] : 1497904
lookup_table[-2] : 3041945510
lookup_table[-1] : 3043453295
Built index in 260.676 s.
CPU time : 478.2 s.
Created threads for align-reads-1 successfully
Command terminated by signal 11

**Comment by jammula** [comment]
Hello! What is the memory size of the compute node you used for this run? Can you try your run using a node with more memory?

**Comment by foodlover1995** [comment]
Hi! Thanks for replying. I saw the error when I run compression on an EC2 instance with 48 vCPU and 96GiB Memory and a container with 86400MiB memory. 
I tried to increase memory with 48 vCPU and 192GiB Memory instance and a container with 172800MiB memory. Although I didn't see "Command terminated by signal 11" again, the compression stuck again after seeing "Created threads for align-reads-1 successfully", which means it still has some issues during aligned reading stage.

Logs:
Reference all_bases_count : 3217346917
Reference val_bases_count : 3043453468
Reference adj_bases_count : 3043453308
Loaded reference into memory in 6.08004 s.
CPU time : 6.08132 s.
lookup_table size is     : 268435457
occurrence_table size is : 3043453295
Created threads for construct-index-1 successfully
Threads for construct-index-1 completed successfully
Before parallel sort
After parallel sort
Created threads for construct-index-2 successfully
Threads for construct-index-2 completed successfully
lookup_table[ 0] : 0
lookup_table[ 1] : 1497904
lookup_table[-2] : 3041945510
lookup_table[-1] : 3043453295
Built index in 111.398 s.
CPU time : 2120.54 s.
Created threads for align-reads-1 successfully

**Comment by jammula** [comment]
> Operation : compression
> Ref File Name : /Homo_sapiens_assembly38.fasta
> Rd1 File Name : /testRefCom/HG001.novaseq.pcr-free.20x.R1.fastq.gz
> Rd2 File Name : /testRefCom/HG001.novaseq.pcr-free.20x.R2.fastq.gz
> Com File Name : /testRefCom/HG001.novaseq.pcr-free.20x.-compressed
> Thread Count : 32

You provided gzip compressed fastq files as input. Currently, the tool only accepts plain fastq files as input. Please decompress read files and provide the decompressed files as input

**Comment by foodlover1995** [comment]
Hi,
Thanks so much. After fixing the input files type, the compression and decompression are working. Thanks for the help. Appreciate!
